Homework (filter)
whoisdaria/itsdone-1 pull request #1
Opened 2020-10-09 11:04 UTC by whoisdaria

1.2. По времени исполнения (вчерашние, сегодняшние, завтрашние, будущие)
---Не сделала, потому что new Date показывает мне неверную дату. Очень непонятно, не разобралась.

Написать функции используя метод .some / .every
---Можно ли в этом случае колбек ф-ии передавать в параметры значение статуса карточки, например? чтобы не писать отдельную проверку на каждый статус

2020-10-09 15:42 UTC, kicumkicum commented
> потому что new Date показывает мне неверную дату. Очень непонятно, не разобралась.

Можешь рассказать подробнее? Что ожидала получить, а что получала

2020-10-09 15:43 UTC, kicumkicum commented
> Можно ли в этом случае колбек ф-ии передавать в параметры значение статуса карточки, например? чтобы не писать отдельную проверку на каждый статус

Не совсем понял, что значит _не писать отдельную проверку на каждый статус_

2020-10-09 15:49 UTC, kicumkicum requested changes

2020-10-09 15:49 UTC, kicumkicum commented on homework/filter.js
> +const cardsStatusInProgress = filterCardsStatus(data.tasks, 'done');
Тут точно нужно передавать статус `'done'`?

2020-10-09 15:49 UTC, kicumkicum commented on homework/filter.js
> +// Результат смотреть через console.log
Но консоль-логов в коде нет. Добавь их пожалуйста, чтобы мне было достаточно запустить код, и не нужно было вносить в него правки

2020-10-09 15:50 UTC, kicumkicum commented
Крутяг! Хорошие решения. Даша, ты молодец 👍🏽

2020-10-10 15:45 UTC, whoisdaria commented
> > потому что new Date показывает мне неверную дату. Очень непонятно, не разобралась.
> 
> Можешь рассказать подробнее? Что ожидала получить, а что получала

const now = new Date();
const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());

console.log(now) 
ожидаю - 2020-10-10T18:37:27.****
получаю - 2020-10-10T15:37:27.****

console.log(today)
ожидаю -  2020-10-10T00:00:00.****
получаю - 2020-10-09T21:00:00.****

2020-10-11 23:13 UTC, kicumkicum commented
Есть время UTC, то бишь по Гринвичу или типа того. 
![image](https://user-images.githubusercontent.com/5058981/95692688-445f6c80-0c30-11eb-93f3-3539bdad197b.png)
У меня new Date возвращает 2 часа, а UTC возвращает на 3 часа меньше. Похоже на твою ситуацию.

Но может у тебя с системным временем что-то не так?

2020-10-19 12:01 UTC, closed without merging